#ifndef _MISR_CONTROL_REG_DEFS_
#define _MISR_CONTROL_REG_DEFS_

// Register width
#define MISR_CONTROL_REG_WIDTH 64

// MISR main control register
#define MISR_CONTROL_CONTROL_REG_OFFSET 0
#define MISR_CONTROL_CONTROL_ENABLE_BIT 0
#define MISR_CONTROL_CONTROL_RESET_BIT 1
#define MISR_CONTROL_CONTROL_DONE_BIT 2

// MISR coefficient register
#define MISR_CONTROL_COEFFICIENTS_REG_OFFSET MISR_CONTROL_REG_WIDTH/8

// MISR signature value
#define MISR_CONTROL_SIGNATURE_REG_OFFSET ((MISR_CONTROL_REG_WIDTH/8)*2)

// MISR peripheral start address
#define MISR_1_PERIPH_START_ADDRESS 0x2000000
#define MISR_2_PERIPH_START_ADDRESS (MISR_1_PERIPH_START_ADDRESS + (MISR_CONTROL_REG_WIDTH/8)*3)

#endif  //_MISR_CONTROL_REG_DEFS_
